### ISSUE TITLE
Does the dv have to be binary？

### ISSUE THREAD

**Issue by MiyeonQAQ** [ehart-altair/SimpsonsParadox#2]
Hi！
I'm reading your code and I wonder does the dv have to be binary?

**Comment by mariamwalaa** [comment]
Hello!

Thanks for your question, and for taking a look at the code!

The DV doesn't have to be binary. You can pass a continuous DV as long as you specify a `model = 'linear'`. 

If you run the Coffee example in the Demo notebook with the continuous DV, the function should be able to accommodate the continuous DV. 

Here's what you would run if you wanted to try the Coffee data example with the continuous DV:

```SimpsonsParadox(df=pd.read_csv('data/coffee_data.csv'), dv='neuroticism', max_pvalue=1, output_plots=True, quiet=True).get_simpsons_pairs()```

Happy to answer more questions!

Mariam

**Comment by MiyeonQAQ** [comment]
Thanks for your reply！
But let me put it more precisely. I have data like this:

A | B | C | D | E | F | G | H | I | J | K | L | M | N
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3.0 | 0.92 | 84 | 86.7 | 80 | 93.3 | 80 | 40 | 100 | 100 | 80 | 2 | 49 | 92
2.0 | 0.93 | 69 | 66.7 | 70 | 73.3 | 80 | 60 | 60 | 80 | 80 | 2 | 60 | 96
3.0 | 0.96 | 67 | 86.7 | 70 | 66.7 | 70 | 80 | 60 | 80 | 80 | 2 | 54 | 93
2.0 | 1.00 | 62 | 86.7 | 70 | 100.0 | 100 | 60 | 80 | 80 | 80 | 3 | 48 | 93
2.0 | 1.00 | 79 | 73.3 | 80 | 86.7 | 80 | 80 | 80 | 60 | 60 | 2 | 55 | 92
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...

To predict ’G‘, a categorical variable with 9 categories, I set 'DV' to 'G'. However I got this:

>SimpsonsParadox-master\simpsons_paradox.py in build_model(self, df, iv)
--> 280                 raise ValueError('You have a non-binary DV. Pass a value to '

>  ValueError: You have a non-binary DV. Pass a value to the target_category in the function or re-bin your DV prior to using the function.

I backtraced the code and found:
`278            elif (self.target_category is None and`
`279                2 < df[self.dv].nunique() <= 10):`
This condition makes the coffee example work but my data fail.
My questions are:

1. What does this condition mean?

2. How can I have the code work on my data, i.e. data with categorical variables having less than 10 categories？

Edit:
When I add 'target_category=1' as it said, I got:
> PerfectSeparationError: Perfect separation detected, results not available

The same error occured when set target_category to 2,3,4,5,6,7,8,9.

**Comment by mariamwalaa** [comment]
Hi, thanks for your reply and for providing more detail!

Oh I see, you want to work with a DV that is not binary but not continuous either. The function will suggest choosing a category to bin if your DV has less than 10 categories. If the function has binned the data but is having issues building the logistic model for the newly binned DV, you will get an error message from the statsmodels library letting you know that there's something called a perfect separation issue that is happening. For example, it's possible that for one of your independent variables, the DV you've chosen is perfectly separating certain observations into certain DV categories. 

We've come across this issue with some of the datasets that we tested, and decided that for the basic demonstration purposes of this function, this issue is too specific to the data and the user will want to investigate their data and the variables that they're using further. 

I'll do a little more digging on this, but to add on to this, the commented code for this function has been made available with some more details in the Wiki, which is here:

https://github.com/ehart-altair/SimpsonsParadox/wiki

And you're welcome to fork the code and make improvements, or make a pull request. I'm also happy to try to answer more questions about this issue or hear out your thoughts or suggestions!

Mariam

**Comment by MiyeonQAQ** [comment]
Hi Mariam!
With more understanding about the algorithm and my dataset, it seems like linear model is what I need instead of 'one-vs-all' logistic regression model. When I add " model='linear' ", everything works!
Great thanks for your well commented code which makes it enjoyable to comprehend!
Nice job!

**Comment by mariamwalaa** [comment]
Thank you, and great to hear! :)
If you have more questions, please feel free to start another issue or send me an email.
